### PR TITLE
#4 Update number picker modal css

### PR DESCRIPTION
**Pull request by groCervo**
Here's the new look

image

### CODE REVIEW

**Comment by Sarthak-Mittal** [comment]
Looks as expected! Is it possible is you could find another solution where you don't have to update styling for `.modal-content` in style.css? In the future, if another modal for some other feature is added, it will also be affected.

**Comment by groCervo** [comment]
Just added a parameter to the open method, that way we can specify the custom css class for each modal

**Comment by Sarthak-Mittal** [comment]
I am sorry, but I do not understand how your latest changes do any good?

**Comment by groCervo** [comment]
I only updated the styling of '.modal-content'  when the parent css class is 'modal-picker'.

That way, when you'r calling the 'open' method in the 'GridComponent' to display a modal, the styling with transparent background will only be applied if yout pass the class 'modal-picker' as last parameter

**Comment by groCervo** [comment]
Does this solution suits you ?

**Comment by Sarthak-Mittal** [comment]
Yes, This works fine. Thanks buddy!

**Comment by Sarthak-Mittal** [comment]
Closed by mistake

**Pull request merged**
